name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Create Release Notes
      id: release_notes
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Generate release notes from git log
        echo "## AutoAI-AgentRAG $VERSION" > release_notes.md
        echo "" >> release_notes.md
        echo "### Changes" >> release_notes.md
        git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"* %s" | grep -v "Merge" >> release_notes.md
        echo "" >> release_notes.md
        echo "### Installation" >> release_notes.md
        echo '```bash' >> release_notes.md
        echo "pip install autoai-agentrag==$VERSION" >> release_notes.md
        echo '```' >> release_notes.md
        
        echo "::set-output name=version::$VERSION"
        cat release_notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.md
        files: |
          dist/*.whl
          dist/*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

